services:
  crud:
    image: spring-boot/crud:1.0.0
    container_name: crud-rest-api
    build:
      dockerfile: Dockerfile
    volumes:
     - ./target/crud-1.0.0.jar:/app/crud.jar
    ports:
     - "8080:8080"

