server:
  port:
    8080
spring:
  application:
    name: SpringBootCrud
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true   # Ejecuta script data.sql después de inicializar Hibernate
    #show-sql: true
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
